'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9179
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ZFDockAuditBMW.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The application will now exit..
        '''</summary>
        Friend ReadOnly Property AppExitMsg() As String
            Get
                Return ResourceManager.GetString("AppExitMsg", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property appicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("appicon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Back].
        '''</summary>
        Friend ReadOnly Property Back() As String
            Get
                Return ResourceManager.GetString("Back", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend ReadOnly Property Data() As String
            Get
                Return ResourceManager.GetString("Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download Master.
        '''</summary>
        Friend ReadOnly Property DownloadMaster() As String
            Get
                Return ResourceManager.GetString("DownloadMaster", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property EmpCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmpCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Exit].
        '''</summary>
        Friend ReadOnly Property ExitApp() As String
            Get
                Return ResourceManager.GetString("ExitApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failure.
        '''</summary>
        Friend ReadOnly Property Failure() As String
            Get
                Return ResourceManager.GetString("Failure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Packaging Control.
        '''</summary>
        Friend ReadOnly Property Item() As String
            Get
                Return ResourceManager.GetString("Item", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item not selected.
        '''</summary>
        Friend ReadOnly Property ItemNotSelected() As String
            Get
                Return ResourceManager.GetString("ItemNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length.
        '''</summary>
        Friend ReadOnly Property Length() As String
            Get
                Return ResourceManager.GetString("Length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan ....
        '''</summary>
        Friend ReadOnly Property Scan() As String
            Get
                Return ResourceManager.GetString("Scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time.
        '''</summary>
        Friend ReadOnly Property Time() As String
            Get
                Return ResourceManager.GetString("Time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property Value() As String
            Get
                Return ResourceManager.GetString("Value", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
